/**
 * This file is part of alf.io.
 *
 * alf.io is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * alf.io is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with alf.io.  If not, see <http://www.gnu.org/licenses/>.
 */

package alfio.repository;

import java.sql.Date;
import java.util.List;
import java.util.UUID;

import alfio.model.vendor.VendorApplication;
import ch.digitalfondue.npjt.*;

@QueryRepository
public interface VendorApplicationRepository {

        @Query("""
                        insert into vendor_applications (applicant_name, store_name, email, phone_number, instagram, portfolio, booth_type_id, status, created_at, event_id, organization_id, description) \
                        values(:applicantName, :storeName, :email, :phoneNumber, :instagram, :portfolio, :boothTypeId, :status, :createdAt, :eventId, :organizationId, :description::text)\
                        """)
        @AutoGeneratedKey("id")
        AffectedRowCountAndKey<Long> insert(
                        @Bind("applicantName") String applicantName,
                        @Bind("storeName") String storeName,
                        @Bind("email") String email,
                        @Bind("phoneNumber") String phoneNumber,
                        @Bind("instagram") String instagram,
                        @Bind("portfolio") String portfolio,
                        @Bind("boothTypeId") UUID boothTypeId,
                        @Bind("status") String status,
                        @Bind("createdAt") Date createdAt,
                        @Bind("eventId") int eventId,
                        @Bind("organizationId") int organizationId,
                        @Bind("description") String description);

        @Query("""
                        select * from vendor_applications where id = :id
                        """)
        VendorApplication findById(@Bind("id") Long id);

        @Query("""
                        select * from vendor_applications where event_id = :eventId
                        """)
        List<VendorApplication> findByEventId(@Bind("eventId") int eventId);

        @Query("""
                        update vendor_applications set status = :status where id = :id
                        """)
        int updateStatus(@Bind("status") String status, @Bind("id") UUID id);

        @Query("""
                        delete from vendor_applications where id = :id
                        """)
        int delete(@Bind("id") Long id);

        @Query("select * from vendor_applications where booth_type_id = :boothTypeId and status = 'APPROVED'")
        List<VendorApplication> findApprovedByBoothTypeId(@Bind("boothTypeId") UUID boothTypeId);

}
