package alfio.repository;

import java.util.List;
import java.util.UUID;

import alfio.model.vendor.VendorBoothType;
import ch.digitalfondue.npjt.AffectedRowCountAndKey;
import ch.digitalfondue.npjt.AutoGeneratedKey;
import ch.digitalfondue.npjt.Bind;
import ch.digitalfondue.npjt.Query;
import ch.digitalfondue.npjt.QueryRepository;

@QueryRepository
public interface VendorBoothTypeRepository {
        @Query("""
                        insert into vendor_booth_types (name, description, status, stock, price, event_id) \
                        values(:name, :description, :status, :stock, :price, :eventId)\
                        """)
        @AutoGeneratedKey("id")
        AffectedRowCountAndKey<UUID> insert(
                        @Bind("name") String name,
                        @Bind("description") String description,
                        @Bind("status") VendorBoothType.BoothTypeStatus status,
                        @Bind("stock") int stock,
                        @Bind("price") double price,
                        @Bind("eventId") int eventId);

        @Query("""
                        select * from vendor_booth_types where id = :id
                                """)
        VendorBoothType findById(@Bind("id") UUID id);

        @Query("select * from vendor_booth_types where event_id = :eventId")
        List<VendorBoothType> findByEventId(@Bind("eventId") int eventId);

        @Query("""
                        update vendor_booth_types set name = :name, description = :description, status = :status, stock = :stock, price = :price where id = :id
                        """)
        int update(
                        @Bind("id") UUID id,
                        @Bind("name") String name,
                        @Bind("description") String description,
                        @Bind("status") VendorBoothType.BoothTypeStatus status,
                        @Bind("stock") int stock,
                        @Bind("price") double price);

        @Query("""
                        delete from vendor_booth_types where id = :id
                        """)
        int delete(@Bind("id") UUID id);

}
